### ISSUE TITLE
SIGSEGV on `alpine launch`

### ISSUE THREAD

**Issue by mzinkus** [beringresearch/macpine#53]
After a clean install on macOS 13.0.1, `alpine launch` fails immediately with:

```
$ › alpine launch
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x104ce048c]

goroutine 1 [running]:
github.com/beringresearch/macpine/utils.DownloadFile({0x140001a8180, 0x35}, {0x14000182660, 0x5c})
	/private/tmp/macpine-20221129-4402-9m69m5/macpine-0.7/utils/utils.go:224 +0x8c
github.com/beringresearch/macpine/qemu.(*MachineConfig).Launch(0x140001992b0)
	/private/tmp/macpine-20221129-4402-9m69m5/macpine-0.7/qemu/ops.go:346 +0x1e4
github.com/beringresearch/macpine/host.Launch({{0x140001aa0f0, 0x12}, {0x140001d02e0, 0x1b}, {0x104da6e7f, 0x7}, {0x104da5dc9, 0x1}, {0x104da61e6, 0x4}, ...})
	/private/tmp/macpine-20221129-4402-9m69m5/macpine-0.7/host/launch.go:23 +0x19c
github.com/beringresearch/macpine/cmd.launch(0x105155c00?, {0x104da6346?, 0x0?, 0x0?})
	/private/tmp/macpine-20221129-4402-9m69m5/macpine-0.7/cmd/launch.go:171 +0x5a0
github.com/spf13/cobra.(*Command).execute(0x105155c00, {0x10518beb8, 0x0, 0x0})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x105156380)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/beringresearch/macpine/cmd.Execute()
	/private/tmp/macpine-20221129-4402-9m69m5/macpine-0.7/cmd/root.go:22 +0x28
main.main()
	/private/tmp/macpine-20221129-4402-9m69m5/macpine-0.7/main.go:6 +0x1c
```

**Comment by idroz** [comment]
Thanks for the report. It looks like an issue with the homebrew binary build for macOS 13.0.1. It was only tested on 12.6

Could you uninstall the homebrew  version of macpine and test by either downloading the latest binary or building from source?

**Comment by mzinkus** [comment]
Same issue

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x10078557c]

goroutine 1 [running]:
github.com/beringresearch/macpine/utils.DownloadFile({0x14000128400, 0x35}, {0x1400010a540, 0x5c})
	/Users/ignat/go/src/github.com/beringresearch/macpine/utils/utils.go:224 +0x8c
github.com/beringresearch/macpine/qemu.(*MachineConfig).Launch(0x14000113040)
	/Users/ignat/go/src/github.com/beringresearch/macpine/qemu/ops.go:346 +0x1e4
github.com/beringresearch/macpine/host.Launch({{0x1400011cb40, 0x10}, {0x1400014e2e0, 0x1b}, {0x10084b828, 0x7}, {0x10084a769, 0x1}, {0x10084ab86, 0x4}, ...})
	/Users/ignat/go/src/github.com/beringresearch/macpine/host/launch.go:23 +0x19c
github.com/beringresearch/macpine/cmd.launch(0x100bf5a80?, {0x10084acea?, 0x0?, 0x0?})
	/Users/ignat/go/src/github.com/beringresearch/macpine/cmd/launch.go:171 +0x5a0
github.com/spf13/cobra.(*Command).execute(0x100bf5a80, {0x100c2bd58, 0x0, 0x0})
	/Users/ignat/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x100bf6200)
	/Users/ignat/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/ignat/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/beringresearch/macpine/cmd.Execute()
	/Users/ignat/go/src/github.com/beringresearch/macpine/cmd/root.go:22 +0x28
main.main()
	/Users/ignat/go/src/github.com/beringresearch/macpine/main.go:6 +0x1c
```

I don't know who `ignat` is, that's not my username. Maybe a maintainer who compiled this? Is that an additional issue?

**Comment by idroz** [comment]
I can't reproduce this seg fault unfortunately - clean installs from the latest binary, source, and brew.

I did notice that the sigsegv error is coming from code that sends a `get` request to download the VM image. The error is being swallowed up with the code and sigsegv is prioritised.

I pushed a quick fix into the master branch, which if installed from source, should return a more informative error message than a sigsegv. Could you give it a go when you have a chance 

You'll need to install macpine from source or use the update binary attached.

[alpine_darwin_arm64.zip](https://github.com/beringresearch/macpine/files/10126836/alpine_darwin_arm64.zip)

**Comment by mzinkus** [comment]
Hah, yep. It's just a network failure due to my firewall

```
2022/11/30 19:24:49 unable to download alpine_3.16.0-aarch64.qcow2 for aarch64: Get "https://github.com/beringresearch/macpine/releases/download/v.01/alpine_3.16.0-aarch64.qcow2": dial tcp 140.82.112.4:443: connect:bad file descriptor
```

Is there any way I can cache this resource locally instead of pulling it from GitHub each time?

**Comment by mzinkus** [comment]
Thanks for your quick response to all of this by the way! I've been struggling to get lightweight virtualization on my M1 Mac and was very excited to see the formula crop up in `brew`

**Comment by idroz** [comment]
>> Is there any way I can cache this resource locally instead of pulling it from GitHub each time?

Yes, macpine caches each image locally after the first download by placing it into the `/Users/$user/.macpine/cache` directory. You'll need to create this directory if doesn't exist and manually download the VM images into it.

Images can be downloaded from [here](https://github.com/beringresearch/macpine/releases/tag/v.01). You'll need both `*qcow2` disk files and the `qemu_efi.fd` firmware file.

**Comment by mzinkus** [comment]
Thank you so much for your help!
